my_robot:
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  wheel_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: wheel_joint
      pid: {p: 200, d: 1, i: 0 }
  
